[mqtt]
vehicle_id = 1
mqtt_server_ip = 192.168.0.100
mqtt_server_port = 1883

[cloud_autonomous_driving]
cloud_server_ip = 192.168.0.112
cloud_server_port = 20001

[steering_calibration]
max = 1630000
mid = 1460000
min = 1180000
